In [1]:
import pandas as pd
import numpy as np

In [4]:
import pandas as pd
import numpy as np

# Create the same data directly
data = {
    'Name': ['John', 'Alice', 'Bob', 'Sara', 'Sam', 'Rohit'],
    'Age': [20, 22, 21, 23, 25, 23],
    'Marks': [85, 90, 78, 92, 90, 45]
}

# Convert to DataFrame
df=pd.DataFrame(data)

# Print the DataFrame
print(df)

# Convert the 'Marks' column to a NumPy array
marks=df['Marks'].to_numpy()

print('\nNumpy Array of Marks:')
print(marks)


    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45

Numpy Array of Marks:
[85 90 78 92 90 45]


In [5]:
print('Highest Marks ',np.max(marks))

Highest Marks  92


In [6]:
print('Lowest Marks ',np.min(marks))

Lowest Marks  45


In [7]:
print('Average Marks ',np.mean(marks))

Average Marks  80.0


# .loc(Label Based)
# .iloc(Index Based)

In [9]:
print(df.loc[2])

Name     Bob
Age       21
Marks     78
Name: 2, dtype: object


In [11]:
print('original dataframe')
print(df)

original dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45


In [18]:
print('Location : Label Based')
print(df.loc[2,['Name','Marks']])

Location : Label Based
Name     Bob
Marks     78
Name: 2, dtype: object


In [17]:
print('Location : Index Based')
print(df.iloc[2,[1,2]])

Location : Index Based
Age      21
Marks    78
Name: 2, dtype: object


# Axis in Numpy : 
    1. Axis 0 : vertical direction: works column-wise
    2. Axis 1 : horizontal direction: works row-wise

# We have two students marks in 3 subjects
# [[45,50,49],[30,45,49]]

In [25]:
marks_arr=np.array([[5,2,9],[10,40,60]])
print(marks_arr)

[[ 5  2  9]
 [10 40 60]]


In [26]:
print('Sum down each column',np.sum(marks_arr,axis=0))

Sum down each column [15 42 69]


In [27]:
print('Sum down each row',np.sum(marks_arr,axis=1))

Sum down each row [ 16 110]


In [28]:
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92 90 45]


In [29]:
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45


# Find the student name who got highest marks

In [33]:
top=df.loc[df['Marks'].idxmax(),'Name']
print('Top Student Name ',top)

Top Student Name  Sara


In [34]:
last=df.loc[df['Marks'].idxmin(),'Name']
print('Last Student Name ',last)

Last Student Name  Rohit


In [36]:
top_index = df['Marks'].idxmax()
top_student = df.iloc[top_index,df.columns.get_loc('Name')]
print('The top student is',top_student)
     

The top student is Sara
