# Numpy Introduction and usage

## One dimensional Array (1-D)

In [2]:
import numpy as np

In [3]:
array1=np.array([10,20,30,40,50])

In [4]:
print(array1)

[10 20 30 40 50]


## Two dimensional Array (2-D)

In [11]:
array_two=np.array([[10,20,30],[40,50,70]])

In [12]:
print(array_two)

[[10 20 30]
 [40 50 70]]


## Three dimensional Array (3-D)

In [16]:
array_three=np.array([[[10,20,30],[40,50,70]],[[10,20,30],[40,50,70]]])

In [17]:
print(array_three)

[[[10 20 30]
  [40 50 70]]

 [[10 20 30]
  [40 50 70]]]


## Find out dimension of NumPy array

In [25]:
print('First Array Dimension: \t', array1.ndim)

First Array Dimension: 	 1


In [23]:
print('Second Array Dimension: \t', array_two.ndim)

Second Array Dimension: 	 2


In [26]:
print('Third Array Dimension: \t', array_three.ndim)

Third Array Dimension: 	 3


# Write an array of 5 students marks using Numpy
 ## Marks are: 80,70,75,99,89

In [35]:
array_marks=np.array([80,70,75,99,89])
print('Array of marks:')
print(array_marks)

Array of marks:
[80 70 75 99 89]


# Write an array to take Marks of 5 students in 3 subjects using Numpy

## Math, English, Chemistry
## [[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]]

In [38]:
marks_subject=np.array([[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]])
print('2 D Array Example')
print(marks_subject)

2 D Array Example
[[50 45 49]
 [40 42 45]
 [35 40 46]
 [39 40 45]
 [48 40 40]]


# Write an array to take Marks of 4 students in 3 subjects for 2 semester using Numpy
## Students Name are 'Amit','Sha','Xi','Arif'
## Math, English, Chemistry
## Two Semester : Sem1, Sem2 
## 4*3*2
## [[85,88],[78,82][90,95]], [[76,70],[40,45][90,90]],[[80,86],[78,82][90,95]],[[85,88],[78,82][70,90]]]

In [41]:
marks_subject_sem=np.array([
    [[85, 88],[78, 82],[90, 95]],
    [[76, 70],[40, 45],[90, 90]],
    [[80, 86],[78, 82],[90, 95]],
    [[85, 88],[78, 82],[70, 90]]])

In [42]:
print(marks_subject_sem)

[[[85 88]
  [78 82]
  [90 95]]

 [[76 70]
  [40 45]
  [90 90]]

 [[80 86]
  [78 82]
  [90 95]]

 [[85 88]
  [78 82]
  [70 90]]]


# Write an array to take weather of 2 cities in 3 days for three times in a day morning, noon, evening
## Cities Name are 'Kuala Lumpur','Delhi'
## Saturday, Sunday, Monday 
## Three Time Slot : Morning, Noon, Evening
432


# Create one 3D Array for this using Numpy and print it

import numpy as np

# Cities and days
cities = ['Kuala Lumpur', 'Delhi']
days = ['Saturday', 'Sunday', 'Monday']
times = ['Morning', 'Noon', 'Evening']

# Create 3D array: shape (2 cities × 3 days × 3 times)


In [48]:
cities_day_time = np.array([
    [  # Kuala Lumpur
        ['Saturday', 'Morning'], ['Saturday', 'Noon'], ['Saturday', 'Evening'],
        ['Sunday', 'Morning'], ['Sunday', 'Noon'], ['Sunday', 'Evening'],
        ['Monday', 'Morning'], ['Monday', 'Noon'], ['Monday', 'Evening']
    ],
    [  # Delhi
        ['Saturday', 'Morning'], ['Saturday', 'Noon'], ['Saturday', 'Evening'],
        ['Sunday', 'Morning'], ['Sunday', 'Noon'], ['Sunday', 'Evening'],
        ['Monday', 'Morning'], ['Monday', 'Noon'], ['Monday', 'Evening']
    ]
])

In [49]:
print(cities_day_time)

[[['Saturday' 'Morning']
  ['Saturday' 'Noon']
  ['Saturday' 'Evening']
  ['Sunday' 'Morning']
  ['Sunday' 'Noon']
  ['Sunday' 'Evening']
  ['Monday' 'Morning']
  ['Monday' 'Noon']
  ['Monday' 'Evening']]

 [['Saturday' 'Morning']
  ['Saturday' 'Noon']
  ['Saturday' 'Evening']
  ['Sunday' 'Morning']
  ['Sunday' 'Noon']
  ['Sunday' 'Evening']
  ['Monday' 'Morning']
  ['Monday' 'Noon']
  ['Monday' 'Evening']]]


# Basic Information

In [51]:
print(array1)

[10 20 30 40 50]


In [52]:
print("Shape of array1 : ",array1.shape)

Shape of array1 :  (5,)


In [53]:
print("Size of array1 : ",array1.size)

Size of array1 :  5


In [54]:
print('Dimension : ',array1.ndim)

Dimension :  1


In [58]:
print('Data Type : ',array1.dtype)

Data Type :  int64


In [60]:
students=np.array(['Ali','Shi','Xi','Meena','Ziva'])

In [61]:
print(students)

['Ali' 'Shi' 'Xi' 'Meena' 'Ziva']


In [62]:
print("Shape of Array : ",students.shape)

Shape of Array :  (5,)


In [64]:
print('Number of students',students.size)

Number of students 5


In [65]:
print('Data Type: ',students.dtype)

Data Type:  <U5


In [66]:
import numpy as np

# Create an array
array1 = np.array([10, 20, 30, 40, 50, 80])

# Print the array
print(array1)

# Sum of all elements
total = np.sum(array1)
print(total)

# Mean of array
print('Mean: ', np.mean(array1))

# Minimum value in array
print('Min: ', np.min(array1))

# Maximum value in array
print('Max: ', np.max(array1))

# Index of minimum value
print('Index of Min: ', np.argmin(array1))

# Index of maximum value
print('Index of Max: ', np.argmax(array1))


[10 20 30 40 50 80]
230
Mean:  38.333333333333336
Min:  10
Max:  80
Index of Min:  0
Index of Max:  5


In [67]:
our_arr=np.array([100,200,300,7000,400,500,300,1900,600])

In [68]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


# Searching and sorting example in 1D Array

In [69]:
sorted_arr=np.sort(our_arr)
print('*** Sorted Array ***')
print(sorted_arr)

*** Sorted Array ***
[ 100  200  300  300  400  500  600 1900 7000]


In [72]:
print('Any item greater than 500 ?: ',np.any(sorted_arr>500))

Any item greater than 500 ?:  True


In [73]:
print('All greater than 500?: ',np.all(sorted_arr>500))

All greater than 500?:  False


In [75]:
print('All greater than 99 ?" ',np.all(sorted_arr>99))

All greater than 99 ?"  True


In [76]:
print('Where values >500',np.where(sorted_arr>500))

Where values >500 (array([6, 7, 8]),)


In [77]:
print('All Number greater than 500')
for num in np.where(sorted_arr>500):
    print(num)

All Number greater than 500
[6 7 8]


In [78]:
print('All Number greater than 500')
for num in sorted_arr>500:
    print(num)

All Number greater than 500
False
False
False
False
False
False
True
True
True


In [80]:
selected_values=sorted_arr[sorted_arr>500]

In [81]:
print(selected_values)

[ 600 1900 7000]


In [82]:
for num in selected_values:
    print (num)

600
1900
7000


In [83]:
for num in sorted_arr[sorted_arr>500]:
    print(num)

600
1900
7000


In [84]:
print(' ',sorted_arr[sorted_arr>500])

  [ 600 1900 7000]


# Slicing 1D Array
    1. To take elements from starting index to end index 
    2. e.g. [start:end]

In [89]:
print(sorted_arr)

[ 100  200  300  300  400  500  600 1900 7000]


In [91]:
slice_sorted_arr=our_arr[1:3]
print(slice_sorted_arr)

[200 300]


# Starting from an index and going till last

In [90]:
print(sorted_arr[3:])

[ 300  400  500  600 1900 7000]


In [92]:
print(sorted_arr[:4])

[100 200 300 300]


In [93]:
print(sorted_arr[:5])

[100 200 300 300 400]


In [94]:
our_slice=sorted_arr[1:6:2]
print(our_slice)

[200 300 500]


In [96]:
every_third_element=sorted_arr[::3]
print(every_third_element)

[100 300 600]


In [97]:
print(sorted_arr)

[ 100  200  300  300  400  500  600 1900 7000]


# Slice Reverse

In [99]:
print('Original Array')
print(sorted_arr)
print('Reverse Array: ',sorted_arr[::-1])

Original Array
[ 100  200  300  300  400  500  600 1900 7000]
Reverse Array:  [7000 1900  600  500  400  300  300  200  100]


In [100]:
print('last five elements')
print(sorted_arr[-5:])

last five elements
[ 400  500  600 1900 7000]
